Id,Nombre,TipoDato,TipoCampoValido,ManejaNivel,Descripcion
1,codigoEvento,String,Evento,0,NULL
2,estadoAperturaCierrePuertas,boolean,Evento,0,NULL
3,estadoErrorCritico,boolean,Evento,0,NULL
4,porcentajeCargaBaterias,double,Evento,0,NULL
5,ciclosApertura,int,Evento,0,NULL
6,horasServicio,int,Evento,0,NULL
7,velocidaMotor,double,Evento,0,NULL
8,fuerzaMotor,double,Evento,0,NULL
9,modoOperacion,int,Evento,0,NULL
10,tipoEnergizacion,int,Evento,0,NULL
11,tipoTramaBusEstacion,String,Evento,0,NULL
12,numeroParada,String,Evento,0,NULL
13,nombreEstacion,String,Evento,0,NULL
14,nombreVagon,String,Evento,0,NULL
15,numeroEventoBusEstacion,int,Evento,0,NULL
16,idVehiculo,String,Evento,0,NULL
17,placaVehiculo,String,Evento,0,NULL
18,tipologiaVehiculo,String,Evento,0,NULL
19,codigoAlarma,String,Alarma,0,NULL
20,tiempoApertura,int,Alarma,0,NULL
21,versionTrama,String,Cabecera,0,NULL
22,idRegistro,String,Cabecera,0,NULL
23,idOperador,String,Cabecera,0,NULL
24,idEstacion,String,Cabecera,0,NULL
25,idVagon,String,Cabecera,0,NULL
26,idPuerta,String,Cabecera,0,NULL
27,codigoPuerta,String,Cabecera,0,NULL
28,fechaHoraLecturaDato,Date,Cabecera,0,NULL
29,fechaHoraEnvioDato,Date,Cabecera,0,NULL
30,tipoTrama,int,Cabecera,0,NULL
31,tramaRetransmitida,boolean,Cabecera,0,NULL
32,activadoDesactivado,boolean,Evento,0,NULL
33,codigoNivelAlarma,String,Alarma,0,NULL
34,usoBotonManual,int,Evento,0,NULL
35,estadoBotonManual,int,Evento,0,NULL
36,porcentajeCargaBaterias,int,Alarma,0,NULL
